server:
  port: 8085
  servlet:
    context-path: /user-service


spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/dev_user_info_system
    username: root
    password: admin
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MariaDBDialect

rsa:
  encryption:
    secret-key:
      public-key: MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQCGT9ikVNbJpYGIW8Roa0+7O7qrrX2YVXN6bx+MRUdGhR3uN0kkF5hzPhDno6omqDBm6uMad0DED/23g5uMU/bXH/bR9ckO7FCgRpnn2xZlzUt3utJVHWbQqYsfewDj8xqas5Dv+3rW4FC7mkUvm7eQDRs2fcMDbIPiuKfOL56RyQIDAQAB
  decryption:
    secret-key:
      private-key: MIICdgIBADANBgkqhkiG9w0BAQEFAASCAmAwggJcAgEAAoGBAIZP2KRU1smlgYhbxGhrT7s7uqutfZhVc3pvH4xFR0aFHe43SSQXmHM+EOejqiaoMGbq4xp3QMQP/beDm4xT9tcf9tH1yQ7sUKBGmefbFmXNS3e60lUdZtCpix97AOPzGpqzkO/7etbgULuaRS+bt5ANGzZ9wwNsg+K4p84vnpHJAgMBAAECgYAd4A3Ww75A/Sz6WTsvZMtH4OnNPRpmM3+ruKMCTvijMYHuVmLRAeSZobEd7TQwRBH8Gnwoi2UfF1V+p+oGBTku3NGJeY4A6k8TMC2OBGytP9nRVYcDU45iCLAudgW9gPVXsaRPayme4+6qHohItu1FohmlfEumpeDT0EqMYLts3wJBAOxVe067ClK/nvrnbS9TpUcOEAPBg2OM5qN+jlpYolq4sy+HHtJzcWil0ZAMAoeVHzAbqHzacLzQqZvLqEXKkW8CQQCRfQi7Peq+f38ZuOK42WuvaULiCnkwfeQsqaH03VW3jnRpEqh4n/WVWqP8AlhoUJ4GQO8XnyQwpzmwr0jmPYRHAkEA515IeatjT9+JJNmsasjY5dc+lm680pj+stETTB+50ldAFSeTZTTfsjOkFgGr+FBlWBO7v3+bHz6ozX10H99QwQJANQKQ1uCVkrmTzwR9n4qg4PYCh6f3RkLoi5l3SGgJHmuKYOqKdgEak0PGckFMgx20pmSseTfkENIthAIqFrIdawJAd4C+aCiCpqVJdyDeIk/C7FWF2/jqRmPUYFxU0hmq/Ai+JlJjjkdhfGDmrAoCX3ZmYiqN4k0PmZWQCab3PE9XGw==
